# disable python warnings if they annoy you
ignore_warnings: False

# ask user for tags if none are provided in the config
enforce_tags: True

# pretty print config tree at the start of the run using Rich library
print_config: False

# https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html
# Sets the internal precision of float32 matrix multiplications.
# highest, high, medium
torch_matmul_precision: high