defaults:
  - /trainer@trainer: tasks/rec
  - _self_

pl:
  _target_: src.llmcrs.models.lightning_modules.KGSFLightning
  is_compile: False
  base_lr: 1e-3
  base_weight_decay: 0
  kg_lr: 1e-3
  kg_weight_decay: 0

  net:
    _target_: src.llmcrs.models.recommendation.KGSF
    n_bases: 8
    kg_dim: 128
    item_dim: 128
    use_bert: True
    use_llm_embedding: False
    use_cl: True
    pooling_method: cls

  optimizer:
    _target_: torch.optim.Adam
    _partial_: true

  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: true
    mode: min
    factor: 0.1
    patience: 3

# model specific trainer configuration
trainer:
  max_epochs: 50
  gradient_clip_val: 0.1
  precision: "bf16-true"
  accumulate_grad_batches: 1